IMAGE_HEIGHT = 45
IMAGE_WIDTH = 45
NUM_LABEL_INDEXES = 14

LABELS = ['OTHER', 'CHECKMARK', 'XMARK', 'LINE_ASCENDING', 'SCRIBBLE', 'CIRCLE'
          , 'SEMICIRCLE_OPEN_UP', 'HEART', 'PLUS_SIGN', 'QUESTION_MARK', 
          'LETTER_A_CAPITAL', 'LETTER_B_CAPITAL', 'FACE_HAPPY', 'FACE_SAD']